@startuml
left to right direction

actor User as User
actor stylus as stylus
rectangle "Operations" {
  User --> (Use tool)
  User --> (Transform style)
  User --> (Create new workspace)
  User --> (Open recent workspace)
  User --> (Create new layer)
  User --> (Duplicate layer)
  User --> (Mask layer)
  User --> (Select tool)
  User --> (Set tool properties)
  User --> (Export file)
  User --> (Import file)
}
  stylus --up--> (Use tool)
actor Ai as Ai
Ai --up--> (Transform style)
@enduml